web_tech_django/apps/blog/urls.py
from django.urls import path

from . import views
from django.contrib import admin


app_name = 'blog'
urlpatterns = [

    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('services', views.services, name='services'),
    path('checkout', views.checkout, name='checkout'),

    # Tours Page
    path('tours', views.tours, name='tours'),
    path('tour/<id>', views.detail_view, name='detail_view'),
    # Search Tour
    path('search_tours', views.search_tours, name='search_tours'),

    # Login / Sign Up / Logout / Admin
    path('admin', admin.site.urls),
    path('signup', views.signUp_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),

    path('base_admin', views.base_admin_view, name='base_admin'),

    # CRUD
    path('add_tour', views.addTour, name='add_tour'),
    path('tours_list', views.tours_list, name='tours_list'),
    path('tour/<id>/edit', views.tour_edit, name='tour_edit'),
    path('tour/<id>/delete', views.tour_delete, name='tour_delete'),
    path('tour/detail/<id>', views.tour_detail, name='tour_detail'),
    path('tour/admin/users_list', views.users_list, name='users_list'),
    path('tour/admin/user_detail/<id>', views.user_detail, name='user_detail'),

# ------- Order Tour urls -------
    path('tour/add_to_cart/<id>', views.add_to_cart, name='add_to_cart'),
    path('order', views.order, name='order'),
    path('order_delete/<id>', views.order_delete, name='order_delete'),

# ------- Hotel urls -------
    path('hotel/add', views.addHotel, name='hotel_add'),
    path('hotel/hotels_list', views.hotels_list, name = 'hotels_list'),
    path('hotel/<id>', views.hotel_detail, name='hotel_detail'),
    path('hotel/<id>/admin', views.hotel_detail_admin, name = 'hotel_detail_admin'),
    path('hotel/<id>/edit', views.hotel_edit, name='hotel_edit'),
    path('hotel/<id>/delete', views.hotel_delete, name='hotel_delete'),

    path('hotel/<id>/orderHotel', views.orderHotel, name='orderHotel'),
    path('myHotelOrders', views.myHotelOrders, name='myHotelOrders'),
    path('hotel/<id>/orderHotelDelete', views.orderHotelDelete, name='orderHotelDelete'),

]

web_tech_django/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web_tech_django/apps/blog/models.py
from django.conf import settings
from django.db import models


class Member(models.Model):
    name = models.CharField('team member', max_length=50)
    number = models.IntegerField('number')
    email = models.CharField('team member', max_length=50)
    position = models.CharField('member position', max_length=50)
    bdate = models.DateTimeField('birth date')

    def __str__(self):
        return self.name


class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=12)
    place = models.CharField(max_length=50)


class Tour(models.Model):
    name = models.CharField('Tour name', max_length=60)
    description = models.TextField('Tour description')
    started = models.DateTimeField('Started date')
    duration = models.IntegerField('Tour duration')
    price = models.IntegerField('Tour price')
    image = models.ImageField('Tour image', upload_to='tours/')
    # customer = models.ManyToManyField(Customer)

    def __str__(self):
        return self.name


class OrderTour(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    # orders =

    def __str__(self):
        return self.tour.name


class Hotel(models.Model):
    name = models.CharField('Hotel name', max_length=60)
    city = models.CharField('Hotel city', max_length=60)
    price = models.IntegerField('Price for one person')
    hotelClass = models.IntegerField('Class of the hotel')
    image = models.ImageField('Tour image', upload_to='hotels/')

    def __str__(self):
        return self.name


class OrderHotel(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)

    def __str__(self):
        return self.hotel.name


# class Order(models.Model):
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     start_date = models.DateTimeField(auto_now_add=True)
#     ordered = models.BooleanField(default=False)
#
#     def __str__(self):
#         return self.user.name

web_tech_django/apps/blog/forms.py
from .models import Tour, Customer, Hotel
from django.forms import ModelForm, TextInput, Textarea, NumberInput, DateInput


class TourForm(ModelForm):
    class Meta:
        model = Tour
        fields = "__all__"
        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control', 'placeholder': 'Enter the name'
            }),
            "description": Textarea(attrs={
                'class': 'form-control', 'placeholder': 'Enter the description'
            }),
            "started": DateInput(attrs={
                'class': 'form-control', 'placeholder': 'Enter started date', 'type': 'date'
            }),
            "price": NumberInput(attrs={
                'class': 'form-control', 'placeholder': 'Enter price of the tour'
            }),
            "duration": NumberInput(attrs={
                'class': 'form-control', 'placeholder': 'Enter duration'
            }),
        }


class HotelForm(ModelForm):
    class Meta:
        model = Hotel
        fields = "__all__"
        # widgets = {
        #     "name": TextInput(attrs={
        #         'class': 'form-control', 'placeholder': 'Enter the name of Hotel'
        #     }),
        #     "city": Textarea(attrs={
        #         'class': 'form-control', 'placeholder': 'Enter the city'
        #     }),
        #     "hotelClass": DateInput(attrs={
        #         'class': 'form-control', 'placeholder': 'Enter the class of a hotel'
        #     }),
        #     "price": NumberInput(attrs={
        #         'class': 'form-control', 'placeholder': 'Enter price of the hotel to the one person'
        #     }),
        # }


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = "__all__"
        widgets = {
            "phone": TextInput(attrs={'class':'form-control'}),
            "place": TextInput(attrs={'class': 'form-control'}),
        }

web_tech_django/apps/blog/views.py
from datetime import datetime

from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail

from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.models import User
from .models import Member, Tour, OrderTour, Customer, Hotel, OrderHotel
from .forms import TourForm, CustomerForm, HotelForm

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required


team_members = ({
    "fname": "Kamran",
    "lname": "Kazemi",
    "bdate": 2003,
    "email": "shahrood@gmail.com",
    "phone": "09999999999",
    "group": "ITTL-1902",
    "position": "Tour Guide"
})

# --------- Site Pages ----------------

def index(request):
    tours = Tour.objects.all()
    todaysDate = datetime.today()
    print( todaysDate)
    return render(request, 'blog/index.html', {'tours': tours, 'todaysDate': todaysDate})


def search_tours(request):
    tours = Tour.objects.all()
    searched_tours = {}

    if request.method == 'POST':
        tourName = request.POST["tourName"]
        tourTravellers = request.POST["tourTravellers"]
        tourDate = request.POST["tourDate"]
        print(tourName)
        print(tourDate)
        if tourName == "none":
            print("with none")
            searched_tours = tours.filter(started__gt=tourDate)
        else:
            print("without none")
            searched_tours = tours.filter(name__contains=tourName) | tours.filter(started__gt=tourDate)

    return render(request, 'blog/tours.html', {'tours': tours, 'searched_tours': searched_tours})


def contact(request):
    members = Member.objects.all()

    return render(request, 'blog/contact.html', {'team': team_members, 'members': members})


def about(request):
    if request.method == 'POST':
        name = request.POST["name"]
        email = request.POST["email"]
        phone = request.POST["phone"]
        text = request.POST["text"]

        subject = 'Welcome to Tour-de-Qaz!'
        message = f'Hi {name}, we are nice to see you! Your number - {phone}, Your email - {email}, Your text - {text}'
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [email, ]
        send_mail(subject, message, email_from, recipient_list)
    return render(request, 'blog/about.html', {'team': team_members})


def services(request):
    hotels = Hotel.objects.all()
    searched_hotels = {}
    if request.method == 'POST':
        cityOrName = request.POST["cityOrName"]
        hotelClass = request.POST["hotelClass"]

        searched_hotels = Hotel.objects.filter(name__contains=cityOrName) | Hotel.objects.filter(city__contains=cityOrName) | Hotel.objects.filter(hotelClass=hotelClass)
    context = {'hotels':hotels, 'searched_hotels': searched_hotels}
    return render(request, 'blog/services.html', context)


def checkout(request):
    return render(request, 'blog/checkout.html')

# ------------- Tour operations -----------------
@login_required(login_url='blog:login')
def addTour(request):
    # create object of form
    form = TourForm(request.POST or None, request.FILES or None)

    # check if form data is valid
    if form.is_valid():
        # save the form data to model
        form.save()
        messages.info(request, "The tour added successfully!")
        return HttpResponseRedirect("/tours_list")

    return render(request, 'blog/../../templates/admin/add_tour.html', {'form': form})


@login_required(login_url='blog:login')
def tour_edit(request, id):
    tour = Tour.objects.get(id=id)
    form = TourForm(instance=tour)

    if request.method == 'POST':
        form = TourForm(request.POST, request.FILES, instance=tour)
        if form.is_valid():
            form.save()
            messages.info(request, "The tour updated successfully!")
            return HttpResponseRedirect("/tours_list")

    return render(request, 'blog/../../templates/admin/tour_edit.html', {'form': form})


def detail_view(request, id):
    tour = Tour.objects.get(id = id)
    return render(request, "blog/detail_view.html", {'tour':tour})


def tour_detail(request, id):
    tour = Tour.objects.get(id = id)
    return render(request, "admin/tour_detail.html", {'tour':tour})


@login_required(login_url='blog:login')
def tour_delete(request, id):
    context = {'id':id}

    # fetch the object related to passed id
    obj = get_object_or_404(Tour, id=id)

    if request.method == "POST":
        if request.POST.get('submit') == 'Yes':
            obj.delete()
            messages.info(request, "The tour Deleted successfully!")
            return HttpResponseRedirect("/tours_list")
        else:
            return HttpResponseRedirect("/tours_list")

    return render(request, "blog/../../templates/admin/tour_delete.html", context)


def tours(request):
    tours = Tour.objects.all()
    # tours.count()
    return render(request, 'blog/tours.html', {'tours': tours})


def tours_list(request):
    context = {'tours': Tour.objects.all()}
    return render(request, 'admin/tours_list.html', context)

# ------------ Login / Sign UP operations -----------------
def signUp_view (request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('blog:tours')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/sign_up.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)

            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('blog:tours')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('blog:index')


@login_required(login_url='blog:login')
def base_admin_view(request):
    return render(request, 'admin/base_admin.html')


@login_required(login_url='blog:login')
def add_to_cart(request, id):
    tour = get_object_or_404(Tour, id=id)
    # tour = Tour.objects.filter(id=id)

    order_item, created = OrderTour.objects.get_or_create(
        tour=tour,
        customer=request.user,
        ordered=True,
    )
    if created:
        messages.info(request, "This item is added to your cart!")
        return redirect("blog:tours")
    else:
        order_item.save()
        messages.info(request, "This item is added to your cart.")
        return redirect("blog:tours")


@login_required
def order(request):
    orders = OrderTour.objects.filter(customer=request.user)
    context = {
        'orders': orders,
    }
    return render(request, 'admin/user/user_order.html', context)


@login_required
def users_list(request):
    orders = OrderTour.objects.filter(customer=request.user, ordered=True)
    users = User.objects.all()
    context = {
        'users': users,
    }
    return render(request, 'admin/user/users_list.html', context)


@login_required
def user_detail(request, id):
    user = User.objects.filter(id=id)
    user_orders = user[0].ordertour_set.all()
    context = {
        'users': user,
        'user_orders': user_orders,
    }
    return render(request, 'admin/user/user_detail.html', context)


@login_required
def order_delete(request, id):
    order = get_object_or_404(OrderTour, id=id)

    if request.method == "POST":
        if request.POST.get('submit') == 'Yes':
            order.delete()
            messages.info(request, "The tour Deleted successfully!")
            return HttpResponseRedirect("/order")
        else:
            return HttpResponseRedirect("/tours_list")

    return render(request, 'admin/user/user_order_delete.html')


# ----------- Hotel views --------------------
@login_required(login_url='blog:login')
def addHotel(request):
    form = HotelForm(request.POST or None, request.FILES or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.info(request, "The Hotel Added Successfully!")
            return HttpResponseRedirect("hotels_list")

    return render(request, 'admin/hotel/add_hotel.html', {'form': form})


@login_required(login_url='blog:login')
def hotel_edit(request, id):
    hotel = Hotel.objects.get(id=id)
    form = HotelForm(instance=hotel)

    if request.method == 'POST':
        form = HotelForm(request.POST, request.FILES, instance=hotel)
        if form.is_valid():
            form.save()
            messages.info(request, "The "+hotel.name+" edited successfully!")
            return HttpResponseRedirect("/hotel/" + id)

    return render(request, 'admin/hotel/hotel_edit.html', {'form': form})


@login_required(login_url='blog:login')
def hotel_delete(request, id):
    context = {'id':id}

    # fetch the object related to passed id
    obj = get_object_or_404(Hotel, id=id)

    if request.method == "POST":
        if request.POST.get('submit') == 'Yes':
            obj.delete()
            messages.info(request, "The Hotel Deleted Successfully!")
            return HttpResponseRedirect("/hotel/hotels_list")
        else:
            return HttpResponseRedirect("/hotel/hotels_list")

    return render(request, "admin/hotel/hotel_delete.html", context)


def hotels_list(request):
    hotels = Hotel.objects.all()
    return render(request, "admin/hotel/hotels_list_admin.html", {'hotels': hotels})


def hotel_detail_admin(request, id):
    hotel = Hotel.objects.get(id=id)
    return render(request, "admin/hotel/hotel_detail_admin.html",{'hotel':hotel})


def hotel_detail(request, id):

web_tech_django/templates/blog/contact.html
{% extends 'base.html' %}

{% block title %}Contacts{% endblock %}

{#{% block active %}active{% endblock %}#}

{% block content %}

    <div class="contact" style="padding: 50px 0;">

    <div class="container text-center">
        <h1 class="display-3">Our Team</h1>

        <div class="row d-grid justify-content-center" style="padding: 50px 0;">
            <div class="card mr-3" style="width: 300px;">
                <img src="../../static/blog/img/2.jpg" class="card-img-top" alt="Sample Image">

{#                With Dictionary ----------#}
                <div class="card-body text-center">
                    <h5 class="card-title">{{ team.fname }} {{ team.lname }}</h5>
                    <p class="card-text">{{ team.position }}</p>
                    <p class="card-text">Group: {{ team.group }}</p>
                    <p class="card-text">Mail: <a href="#">{{ team.email }}</a></p>
                    <p class="card-text">Phone Number: {{ team.phone }}</p>
                    <a href="#" class="btn btn-primary">View Profile</a>
                </div>
             </div>

{#            With Models  ---------------#}
            {% for member in members %}
            <div class="card mr-3" style="width: 300px;">
                <img src="../../static/blog/img/mine.jpg" class="card-img-top" alt="Sample Image">
                <div class="card-body text-center">
                    <h5 class="card-title">{{ member.name }}</h5>
                    <p class="card-text">{{ member.position }}</p>
                    <p class="card-text">Mail: <a href="#">{{ member.email|center:"5" }}</a></p>
                    <p class="card-text">
                        {% if member.number|length == 12 %}
                            Phone Number: {{ member.number }}
                        {% else %}
                            Phone Number is doesn't exist!
                        {% endif %}
                    </p>
                    <a href="#" class="btn btn-primary">View Profile</a>
                </div>
             </div>
            {% endfor %}
        </div>
    </div>

    </div>

{% endblock %}

web_tech_django/templates/blog/detail_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Tour Detail {% endblock %}

{% block content %}

    <div class="showcase">
        <div class="container">
            <div class="showcase__text">
                {{ tour.name }}
            </div>
        </div>
    </div>

    <div class="tour" style="margin: 50px 0;">
        <div class="container">

            <div class="row">

                <div class="col-lg-6 ">
                    <img class="img-fluid rounded" src="{% static "uploads/" %}{{ tour.image }}" alt="" height="400px">
                </div>

                <div class="col-lg-6 ">
                    <div class="tour__desc">
                    Description: <br><br> {{ tour.description }}
                    </div>
                    <br>
                    <div > Duration of the tour: - {{ tour.duration }}</div>
                    <br>
                    <div > Start Day: - {{ tour.started }}</div>
                    <br>
                    <div > Price of the tour: - {{ tour.price }}</div>
                    <br>
                    <br>
                    <a href="{% url 'blog:add_to_cart' id=tour.id %}" class="btn">Order</a>
            </div>

            </div>

        </div>


    </div>

{% endblock %}

web_tech_django/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Main Page{% endblock %}

{% block content %}

    <div class="enjoy">
				<div class="enjoy__row">
					<div class="enjoy__body">
						<div class="enjoy__title">Let's enjoy your <br> vacations</div>
						<div class="enjoy__text">There are many variations of passages. Find out what the best destinations in the world are as awarded by millions of real.</div>
					</div>
					<div class="enjoy__search">
						<form action="{% url 'blog:search_tours' %}" method="post">
                            {% csrf_token %}
							To
							<select name="tourName" id="search__places">
                                <option selected value="none">Select name</option>
                                {% for tour in tours %}
                                    <option  value="{{ tour.name }}">{{ tour.name }}</option>
                                {% endfor %}
							</select>     

							Travellers
							<input type="number" name="tourTravellers" id="search__travelers" value="1">

							 Departure
                            <input type="date" id="search__date" name="tourDate" value="{{ todaysDate|date:"Y-m-d" }}">
                     <!-- <div>
                     	<label for="round">
                     	<input id="round" type="radio" value="">Round
                     </label>
                     
                     <label for="oneway">
                     	<input id="oneway" type="radio" value="">Oneway
                     </label>
                     </div> -->

							<button class="btn__rev" type="submit">
								Submit
							<!-- <img src="{% static 'blog/img/icons/search3.png' %}" alt=""> -->
							</button>

						</form>
					</div>
				</div>
		</div>

    <div class="container">

		<section class="services">
			<div class="container">
				<div class="services__header text-center">
					<h1>Our Best Services</h1>
					<div class="lead">Why we are the best for our client</div>
				</div>
				<div class="services__row">
					<div class="services__features">
					<div class="features__item item1">
						<div class="item__title">A lot of Discount</div>
						<div class="item__text text">
							Find out what the best destinations in the world are as awarded by millions of real.
						</div>
					</div>
					<div class="features__item item2">
						<div class="item__title">Best Guide</div>
						<div class="item__text text">
							Find out what the best destinations in the world are as awarded by millions of real.
						</div>
					</div>
					<div class="features__item item3">
						<div class="item__title">Management</div>
						<div class="item__text text">
							Find out what the best destinations in the world are as awarded by millions of real.
						</div>
					</div>
					</div>
					<div class="services__image">
						<img src="{% static 'blog/img/enjoy.jpg' %}" alt="">
					</div>
				</div>
			</div>
		</section>

		<div class="slider">

			<h1 class="h1 text-center title">Our Best Places</h1>

			<div id="demo" class="carousel slide row" data-ride="carousel">

			  <!-- Indicators -->
			  <ul class="carousel-indicators">
			    <li data-target="#demo" data-slide-to="0" class="active"></li>
			    <li data-target="#demo" data-slide-to="1"></li>
			    <li data-target="#demo" data-slide-to="2"></li>
			  </ul>

			  <!-- The slideshow -->
			  <div class="carousel-inner">
				    <div class="carousel-item active slider__img1 slider__img">
				      <!-- <img src="img/enjoy.jpg" alt="Los Angeles"> -->
				    </div>
				    <div class="carousel-item slider__img2 slider__img">
				      <!-- <img src="img/showcase.jpg" alt="Chicago"> -->
				    </div>
				    <div class="carousel-item slider__img3 slider__img">
				      <!-- <img src="img/tours1.png" alt="New York"> -->
				    </div>
			  </div>

			  <!-- Left and right controls -->
			  <a class="carousel-control-prev" href="#demo" data-slide="prev">
			    <span class="carousel-control-prev-icon"></span>
			  </a>
			  <a class="carousel-control-next" href="#demo" data-slide="next">
			    <span class="carousel-control-next-icon"></span>
			  </a>
			</div>
		</div>

		<div class="packages">
			<div class="container">
				<div class="packages__header">
					<div class="packages__title">Our Most Popular Packages</div>
					<div class="packages__subtitle">Find out what the best destinations in the Qazaqstan</div>
				</div>
				<div class="row centered">
					<div class="col-md-4 packages__column">
						<img src="{% static 'blog/img/tours/borovoe-1.jpg' %}" alt="" class="img-fluid">
						<div class="col__body">
							<div class="col__name">Babol</div>
							<div class="col__place">North Iran</div>
						</div>
					</div>
					<div class="col-md-4 packages__column" >
						<img src="{% static 'blog/img/tours/altyn-emel_4.jpg' %}" alt="" class="img-fluid">
						<div class="col__body">
							<div class="col__name">Bushehr</div>
							<div class="col__place">south Iran</div>
						</div>
					</div>
					<div class="col-md-4 packages__column">
						<img src="{% static 'blog/img/tours/ornitology_5.jpg' %}" alt="" class="img-fluid">
						<div class="col__body">
							<div class="col__name">Tehran</div>
							<div class="col__place">Capital of Iran</div>
						</div>
					</div>
				</div>
			</div>
		</div>

    </div>

{% endblock %}

web_tech_django/templates/blog/services.html
{% extends 'base.html' %}
{% load static %}
{#{% extends 'admin/base_admin.html' %}#}

{% block title %} Services {% endblock %}

{# {% block link %}#}
{#        <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">#}
{#    {% endblock %}#}

{% block content %}

    <div class="showcase">
		<div class="showcase__block">
			<div class="showcase__text">
				Services
			</div>
		</div>
	</div>

        <section class="hotels">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-md-8 text-center hotels__header">
                    <h2>Hotels</h2>
                    <p>Find the best hotel that you need!</p>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-9">
                    <form action="" method="post" class="hotels__form">
                        {% csrf_token %}
                        <input type="text" class="form-control" placeholder="City, Name of the Hotel" name="cityOrName">
                        <select class="form-select" aria-label="Default select example" name="hotelClass">
                              <option selected value="1">Hotel class</option>
                              <option value="1">One</option>
                              <option value="2">Two</option>
                              <option value="3">Three</option>
                              <option value="4">Four</option>
                              <option value="5">Five</option>
                        </select>
                        <button type="submit" class="btn__rev">Search</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

    {% if searched_hotels %}
        <div class="container mt-4 p-4">
            <h1 class="d-flex justify-content-center p-4 font-weight-bold display-5">Hotels that you needed!</h1>
            <div class="row">
                {% for hotel in searched_hotels %}
                    <div class="col-md-4 mb-3 card__body">
                        <div class="card">
                            <div class="card__img"><img class="img-fluid" alt="100%x280" src="{% static "uploads/" %}{{ hotel.image }}"></div>
                            <div class="card-body">
                                <h4 class="card-title">{{ hotel.name }}</h4>
                                <p class="card-text">{{ hotel.city }}</p>
                                <p class="card-text">{{ hotel.hotelClass }}-stars</p>
                                <p class="card-text">{{ hotel.price }}</p>
                                <a href="{% url 'blog:hotel_detail' id=hotel.id %}" class="btn btn__rev">More</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
			</div>
        </div>
    {% endif %}

    <section class="showcases">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 order-lg-2 showcases__img" style="background-image: url({% static 'blog/img/tours/KazakhEagleHunter.jpg' %})"></div>
                <div class="col-lg-6 order-lg-1 showcases__text my-auto">
                    <h2>A lot of Discount</h2>
                    <p class="lead">Find out what the best destinations in the world are as awarded by millions of real.</p>
                    <div style="width: 100px;margin-top: 20px;"><button class="btn__rev">More</button></div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 showcases__img" style="background-image: url({% static 'blog/img/tours/yourta.jpg' %})"></div>
                <div class="col-lg-6 showcases__text my-auto">
                    <h2>Best Guide</h2>
                    <p class="lead">Find out what the best destinations in the world are as awarded by millions of real.</p>
                    <div style="width: 100px;margin-top: 20px;"><button class="btn__rev">More</button></div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 order-lg-2 showcases__img" style="background-image: url({% static 'blog/img/tours/borovoe-1.jpg' %})"></div>
                <div class="col-lg-6 order-lg-1 showcases__text my-auto">
                    <h2>Management</h2>
                    <p class="lead">Find out what the best destinations in the world are as awarded by millions of real.</p>
                    <div style="width: 100px;margin-top: 20px;"><button class="btn__rev">More</button></div>
                </div>
            </div>
        </div>
    </section>



{#    <section class="hotel_cards pt-5 pb-5">#}
{#        <div class="container">#}
{#            <div class="row">#}
{#                {% for hotel in hotels %}#}
{#                    <div class="col-md-4 mb-3 card__body">#}
{#                        <div class="card">#}
{#                            <div class="card__img"><img class="img-fluid" alt="100%x280" src="{% static "uploads/" %}{{ hotel.image }}"></div>#}
{#                            <div class="card-body">#}
{#                                <h4 class="card-title">{{ hotel.name }}</h4>#}
{#                                <p class="card-text">{{ hotel.city }}</p>#}
{#                                <p class="card-text">{{ hotel.hotelClass }}-stars</p>#}
{#                                <p class="card-text">{{ hotel.price }}</p>#}
{#                                <button class="btn__rev">More</button>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                {% endfor %}#}
{#			</div>#}
{#		</div>#}
{#    </section>#}


{% endblock %}