web_tech_django/apps/blog/urls.py
from django.urls import path

from . import views
from django.contrib import admin


app_name = 'blog'
urlpatterns = [

    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('services', views.services, name='services'),
    path('checkout', views.checkout, name='checkout'),

    # Tours Page
    path('tours', views.tours, name='tours'),
    path('tour/<id>', views.detail_view, name='detail_view'),
    # Search Tour
    path('search_tours', views.search_tours, name='search_tours'),

    # Login / Sign Up / Logout / Admin
    path('admin', admin.site.urls),
    path('signup', views.signUp_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),

    path('base_admin', views.base_admin_view, name='base_admin'),

    # CRUD
    path('add_tour', views.addTour, name='add_tour'),
    path('tours_list', views.tours_list, name='tours_list'),
    path('tour/<id>/edit', views.tour_edit, name='tour_edit'),
    path('tour/<id>/delete', views.tour_delete, name='tour_delete'),
    path('tour/detail/<id>', views.tour_detail, name='tour_detail'),
    path('tour/admin/users_list', views.users_list, name='users_list'),
    path('tour/admin/user_detail/<id>', views.user_detail, name='user_detail'),

# ------- Order Tour urls -------
    path('tour/add_to_cart/<id>', views.add_to_cart, name='add_to_cart'),
    path('order', views.order, name='order'),
    path('order_delete/<id>', views.order_delete, name='order_delete'),

# ------- Hotel urls -------
    path('hotel/add', views.addHotel, name='hotel_add'),
    path('hotel/hotels_list', views.hotels_list, name = 'hotels_list'),
    path('hotel/<id>', views.hotel_detail, name='hotel_detail'),
    path('hotel/<id>/admin', views.hotel_detail_admin, name = 'hotel_detail_admin'),
    path('hotel/<id>/edit', views.hotel_edit, name='hotel_edit'),
    path('hotel/<id>/delete', views.hotel_delete, name='hotel_delete'),

    path('hotel/<id>/orderHotel', views.orderHotel, name='orderHotel'),
    path('myHotelOrders', views.myHotelOrders, name='myHotelOrders'),
    path('hotel/<id>/orderHotelDelete', views.orderHotelDelete, name='orderHotelDelete'),

]

web_tech_django/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web_tech_django/templates/accounts/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>

    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}">
</head>
<body>

    <div class="login">
        <div class="login-form">
            <form action="#" class="item__form" method="post">
                {% csrf_token %}

                {% if request.GET.next %}
                    <h1>Please login first, before this operation!</h1>
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}

                {{ form }}<br>

                <input type="submit" value="Login" class="btn">

                <br><br>

                <div class="login-signup">
                    <p>No an account?!</p>
                    <a href="{% url 'blog:signup' %}" class="btn">Sign Up</a>
                </div>
        </form>
        </div>
    </div>


</body>
</html>

web_tech_django/templates/accounts/sign_up.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Sign Up {% endblock %}
{#{% block style-link %}{% static 'blog/css/style.css' %}{% endblock %}#}

{% block content %}

<div class="wrapper">
    <div class="login">
        <div class="login-form">
            <form action="#" method="post" class="item__form" style="width: 500px;">
                {% csrf_token %}
                    {{ form }}<br>
                    <input type="submit" value="Sign Up" class="btn">
                    <br><br>
                    <div class="login-signup">
                        <p>Already have an account?!</p>
                        <a href="{% url 'blog:login' %}" class="btn">Login</a>
                    </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}