web_tech_django/apps/blog/urls.py
from django.urls import path

from . import views
from django.contrib import admin


app_name = 'blog'
urlpatterns = [

    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('services', views.services, name='services'),
    path('checkout', views.checkout, name='checkout'),

    # Tours Page
    path('tours', views.tours, name='tours'),
    path('tour/<id>', views.detail_view, name='detail_view'),
    # Search Tour
    path('search_tours', views.search_tours, name='search_tours'),

    # Login / Sign Up / Logout / Admin
    path('admin', admin.site.urls),
    path('signup', views.signUp_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),

    path('base_admin', views.base_admin_view, name='base_admin'),

    # CRUD
    path('add_tour', views.addTour, name='add_tour'),
    path('tours_list', views.tours_list, name='tours_list'),
    path('tour/<id>/edit', views.tour_edit, name='tour_edit'),
    path('tour/<id>/delete', views.tour_delete, name='tour_delete'),
    path('tour/detail/<id>', views.tour_detail, name='tour_detail'),
    path('tour/admin/users_list', views.users_list, name='users_list'),
    path('tour/admin/user_detail/<id>', views.user_detail, name='user_detail'),

# ------- Order Tour urls -------
    path('tour/add_to_cart/<id>', views.add_to_cart, name='add_to_cart'),
    path('order', views.order, name='order'),
    path('order_delete/<id>', views.order_delete, name='order_delete'),

# ------- Hotel urls -------
    path('hotel/add', views.addHotel, name='hotel_add'),
    path('hotel/hotels_list', views.hotels_list, name = 'hotels_list'),
    path('hotel/<id>', views.hotel_detail, name='hotel_detail'),
    path('hotel/<id>/admin', views.hotel_detail_admin, name = 'hotel_detail_admin'),
    path('hotel/<id>/edit', views.hotel_edit, name='hotel_edit'),
    path('hotel/<id>/delete', views.hotel_delete, name='hotel_delete'),

    path('hotel/<id>/orderHotel', views.orderHotel, name='orderHotel'),
    path('myHotelOrders', views.myHotelOrders, name='myHotelOrders'),
    path('hotel/<id>/orderHotelDelete', views.orderHotelDelete, name='orderHotelDelete'),

]

web_tech_django/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web_tech_django/templates/base.html
{% load static %}
{#{% use %}#}
<!DOCTYPE html>
<html lang="en">
<head>
	 <meta name="viewport"
     content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

	<title>
        {% block title %}My Site{% endblock %}
    </title>

<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="{% static 'blog/css/extra/bootstrap.min.css' %}">

<link
   href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
   rel="stylesheet"
   integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
   crossorigin="anonymous"
   />
 <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>

<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script> -->


<!-- <link rel="stylesheet" href="{% static 'blog/css/extra/mdb.min.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/extra/style.min.css' %}"> -->

<link rel="stylesheet" href="{% static 'blog/css/index.css' %}">


</head>

<body>

{% if messages %}

    {% for message in messages %}
        <div class="alert alert-warning d-flex justify-content-center" role="alert" style="margin-top: 50px;padding: 25px;">
            {{ message }}
        </div>
    {% endfor %}

{% endif %}

<div class="wrapper">

        <nav id="header" class="navbar navbar-expand-lg navbar-dark fixed-top">
          <div class="container">
            <a href="{% url 'blog:index' %}" class="logo navbar-brand ">Wunderlust Advanture</a>
            <button
              class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navmenu"
            >
              <span class="navbar-toggler-icon "></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navmenu">
              <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                  <a href="{% url 'blog:index' %}" class="nav-link {% block active %}{% endblock %}">Home</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'blog:tours' %}" class="nav-link">Tours</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'blog:services' %}" class="nav-link">Services</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'blog:about' %}" class="nav-link">About Us</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
                </li>
                <li class="nav-item">
                   <a class="nav-link" href="{% url 'blog:base_admin' %}" role="button"><i class="fa fa-user fa-fw"></i></a>
                </li>

{#                {% if user.is_authenticated %}#}
{#                    <li class="nav-item">#}
{#                        <form action="{% url 'blog:logout' %}" method="post">#}
{#                            {% csrf_token %}#}
{#                            <button type="submit" class="nav-link bg-light">Logout</button>#}
{#                        </form>#}
{#                    </li>#}
{#                {% else %}#}
{#                    <li class="nav-item">#}
{#                        <a href="{% url 'blog:login' %}" class="nav-link">Login</a>#}
{#                    </li>#}
{#                {% endif %}#}

              </ul>
            </div>
          </div>
        </nav>

    <div class="content">

        {% block content %}

	    {% endblock %}

    </div>

    <footer class="footer">
		<div class="container">
			<div class="footer__row">
				<div class="footer__body">
					<div class="footer__logo">
						<a href="{% url 'blog:index' %}">Wunderlust Advanture</a>
					</div>
					<div class="footer__subtitle">Find out what the best destinations in the Qazaqstan.</div>
					<div class="footer__soc-media">
						<a href="https://www.twitter.com/0x27752357/"><img src="{% static 'blog/img/icons/twitter.png' %}" alt=""></a>
						<a href="https://www.telegram.com/@ssaabriiii/"><img src="{% static 'blog/img/icons/telegram.png' %}" alt=""></a>
						<a href="https://www.instagram.com/0x27752357/"><img src="{% static 'blog/img/icons/instagram.png' %}" alt=""></a>
						<a href="https://www.facebook.com/0x27752357/"><img src="{% static 'blog/img/icons/facebook.png' %}" alt=""></a>
						<a href="https://www.twitter.com/0x27752357/"><img src="{% static 'blog/img/icons/linkedin.png' %}" alt=""></a>
						<a href="https://www.twitter.com/0x27752357/"><img src="{% static 'blog/img/icons/youtube.png' %}" alt=""></a>
					</div>
                    {% now "Y" as current_year %}
					<div class="footer__rights">Copyright &copy;{{ current_year }} WunderlustAdvanture. All rights reserved. </div>
				</div>
				<div class="footer__links">
					<div class="link-col">
					<div class="link__title">Wunderlust Advanture</div>
						<a href="blog/index.html">Home</a>
						<a href="#">Tours</a>
						<a href="blog/about.html">About Us</a>
                        <a href="{% url 'blog:add_tour' %}">Add Tour</a>
                        <a href="{% url 'blog:base_admin' %}">Admin</a>
					</div>
					<div class="link-col">
						<div class="link__title">Help</div>
						<a href="#">Privacy Policy</a>
						<a href="#">Term & Conditions</a>
                        <a href="{% url 'blog:contact' %}">Contacts</a>
                        <a href="{% url 'blog:checkout' %}">Checkout</a>
					</div>
				</div>
			</div>
		</div>
	</footer>
</div>



<script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


<script>

  // $(document).on("scroll",function(){
  //   if($(window).scrollTop() === 0)
  //     $("nav").removeClass("nav-bg");
  //   else
  //     $("nav").attr("class", "nav-bg");
  // });

  document.addEventListener("DOMContentLoaded", function(){
  window.addEventListener('scroll', function() {
      if (window.scrollY > 200) {
        document.getElementById('header').classList.add('bg-primary');
        // add padding top to show content behind navbar
        // navbar_height = document.querySelector('.navbar').offsetHeight;
        // document.body.style.paddingTop = navbar_height + 'px';
      } else {
        document.getElementById('header').classList.remove('bg-primary');
         // remove padding top from body
        // document.body.style.paddingTop = '0';
      } 
  });
});

 </script>



</body>
</html>